import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'it';

const translations: Record<string, Record<Language, string>> = {
  'Revenue Intelligence': { en: 'Revenue Intelligence', it: 'Intelligence Ricavi' },
  'AI Advisor': { en: 'AI Advisor', it: 'Consulente AI' },
  'Season Pacing': { en: 'Season Pacing', it: 'Andamento Stagionale' },
  'Ahead of Pace': { en: 'Ahead of Pace', it: 'Sopra il Ritmo' },
  'Behind Pace': { en: 'Behind Pace', it: 'Sotto il Ritmo' },
  'ON PACE': { en: 'ON PACE', it: 'IN LINEA' },
  'AHEAD PACE': { en: 'AHEAD PACE', it: 'SOPRA IL RITMO' },
  'BEHIND PACE': { en: 'BEHIND PACE', it: 'SOTTO IL RITMO' },
  'surplus': { en: 'surplus', it: 'surplus' },
  'gap': { en: 'gap', it: 'gap' },
  'Revenue Verticals': { en: 'Revenue Verticals', it: 'Verticali Ricavi' },
  'Strategic Signals': { en: 'Strategic Signals', it: 'Segnali Strategici' },
  'Projected Finish': { en: 'Projected Finish', it: 'Proiezione Fine Stagione' },
  'GameDay Projection': { en: 'GameDay Projection', it: 'Proiezione GameDay' },
  'GameDay Tickets Projection': { en: 'GameDay Tickets Projection', it: 'Proiezione Biglietti GameDay' },
  'Attention Required': { en: 'Attention Required', it: 'Attenzione Richiesta' },
  'Coming Soon': { en: 'Coming Soon', it: 'In Arrivo' },
  'Progress': { en: 'Progress', it: 'Progresso' },
  'Accounted': { en: 'Accounted', it: 'Contabilizzato' },
  'Pace': { en: 'Pace', it: 'Ritmo' },
  'Proj': { en: 'Proj', it: 'Proiez' },
  'Target': { en: 'Target', it: 'Obiettivo' },
  'Collected': { en: 'Collected', it: 'Incassato' },
  'Recognized': { en: 'Recognized', it: 'Riconosciuto' },
  'Signed': { en: 'Signed', it: 'Firmato' },
  'Overview': { en: 'Overview', it: 'Panoramica' },
  'CRM': { en: 'CRM', it: 'CRM' },
  'Comparison': { en: 'Comparison', it: 'Confronto' },
  'Simulator': { en: 'Simulator', it: 'Simulatore' },
  'Home': { en: 'Home', it: 'Home' },
  'Ticketing': { en: 'Ticketing', it: 'Biglietteria' },
  'GameDay': { en: 'GameDay', it: 'GameDay' },
  'Sponsorship': { en: 'Sponsorship', it: 'Sponsorizzazioni' },
  'Merchandising': { en: 'Merchandising', it: 'Merchandising' },
  'Venue Ops': { en: 'Venue Ops', it: 'Operazioni Venue' },
  'Varese Basketball': { en: 'Varese Basketball', it: 'Varese Basketball' },
  'BOps': { en: 'BOps', it: 'BOps' },
  'Modules': { en: 'Modules', it: 'Moduli' },
  'Ticketing Tools': { en: 'Ticketing Tools', it: 'Strumenti Biglietteria' },
  'Data Source': { en: 'Data Source', it: 'Fonte Dati' },
  'Latest Game': { en: 'Latest Game', it: 'Ultima Partita' },
  'Refresh Data': { en: 'Refresh Data', it: 'Aggiorna Dati' },
  '3-Season Revenue Trend': { en: '3-Season Revenue Trend', it: 'Trend Ricavi 3 Stagioni' },
  'behind expected': { en: 'behind expected', it: 'sotto le attese' },
  'pace': { en: 'pace', it: 'ritmo' },
  'Gap': { en: 'Gap', it: 'Gap' },
  'games': { en: 'games', it: 'partite' },
  'Full Year': { en: 'Full Year', it: 'Anno Intero' },
  'vs target': { en: 'vs target', it: 'vs obiettivo' },
  'GameDay view tickets': { en: 'GameDay view tickets', it: 'Biglietti vista GameDay' },
  'Tickets sold on game day': { en: 'Tickets sold on game day', it: 'Biglietti venduti il giorno della partita' },
  'Accounting': { en: 'Accounting', it: 'Contabile' },
  'Realistic': { en: 'Realistic', it: 'Realistico' },
  'Board Report': { en: 'Board Report', it: 'Report CDA' },
  'Upload': { en: 'Upload', it: 'Carica' },
  'Settings': { en: 'Settings', it: 'Impostazioni' },

  'Executive Overview': { en: 'Executive Overview', it: 'Panoramica Generale' },
  'Executive Summary': { en: 'Executive Summary', it: 'Riepilogo Esecutivo' },
  'Risk Assessment': { en: 'Risk Assessment', it: 'Valutazione Rischi' },
  'Top Opportunities': { en: 'Top Opportunities', it: 'Opportunità Principali' },
  'YoY Comparison': { en: 'YoY Comparison', it: 'Confronto Anno su Anno' },
  'STRATEGIC ASSESSMENT': { en: 'STRATEGIC ASSESSMENT', it: 'VALUTAZIONE STRATEGICA' },
  'games played': { en: 'games played', it: 'partite giocate' },

  'Data Management': { en: 'Data Management', it: 'Gestione Dati' },
  'Select a specific vertical to manage its data.': { en: 'Select a specific vertical to manage its data.', it: 'Seleziona un verticale specifico per gestire i dati.' },
  'Data View': { en: 'Data View', it: 'Vista Dati' },
  'Total View': { en: 'Total View', it: 'Vista Totale' },
  'GameDay Only': { en: 'GameDay Only', it: 'Solo GameDay' },
  'Global Overview Mode': { en: 'Global Overview Mode', it: 'Modalità Panoramica Globale' },
  'Monthly Reports': { en: 'Monthly Reports', it: 'Report Mensili' },
  'GameDay Tools': { en: 'GameDay Tools', it: 'Strumenti GameDay' },
  'Dashboard': { en: 'Dashboard', it: 'Dashboard' },
  'View Configuration': { en: 'View Configuration', it: 'Configurazione Vista' },
  'Include Ticketing': { en: 'Include Ticketing', it: 'Includi Biglietteria' },

  'Active Filters': { en: 'Active Filters', it: 'Filtri Attivi' },
  'Clear All': { en: 'Clear All', it: 'Cancella Tutto' },
  'Season': { en: 'Season', it: 'Stagione' },
  'League': { en: 'League', it: 'Campionato' },
  'Opponent': { en: 'Opponent', it: 'Avversario' },
  'Zone': { en: 'Zone', it: 'Zona' },
  'Tier': { en: 'Tier', it: 'Fascia' },
  'All': { en: 'All', it: 'Tutti' },

  'Trend & Performance Analysis': { en: 'Trend & Performance Analysis', it: 'Analisi Trend e Performance' },
  'Ticket Pricing Breakdown': { en: 'Ticket Pricing Breakdown', it: 'Dettaglio Prezzi Biglietti' },
  'Tickets by Type': { en: 'Tickets by Type', it: 'Biglietti per Tipo' },
  'Venue Intelligence': { en: 'Venue Intelligence', it: 'Intelligence Arena' },

  'of H1 budget': { en: 'of H1 budget', it: 'del budget H1' },
  'achieved': { en: 'achieved', it: 'raggiunto' },

  'Financial Overview (Per Game Avg)': { en: 'Financial Overview (Per Game Avg)', it: 'Panoramica Finanziaria (Media per Partita)' },
  'Total GameDay Rev': { en: 'Total GameDay Rev', it: 'Ricavi Totali GameDay' },
  'GameDay Rev (Net)': { en: 'GameDay Rev (Net)', it: 'Ricavi GameDay (Netti)' },
  'Variable Ops (Total)': { en: 'Variable Ops (Total)', it: 'Ops Variabili (Totale)' },
  'Rev Per Head': { en: 'Rev Per Head', it: 'Ricavo Per Persona' },
  'Avg Sponsorship': { en: 'Avg Sponsorship', it: 'Sponsorizzazione Media' },
  'Avg TV Rights': { en: 'Avg TV Rights', it: 'Diritti TV Medi' },
  'Avg Ticketing': { en: 'Avg Ticketing', it: 'Biglietteria Media' },
  'Operational Variable Mix (Avg Per Game)': { en: 'Operational Variable Mix (Avg Per Game)', it: 'Mix Variabile Operativo (Media per Partita)' },
  'Hospitality': { en: 'Hospitality', it: 'Ospitalità' },
  'Parking': { en: 'Parking', it: 'Parcheggio' },
  'Experiences': { en: 'Experiences', it: 'Esperienze' },
  'Food & Beverage': { en: 'Food & Beverage', it: 'Food & Beverage' },
  'Total Revenue Mix by Match (Incl. Tix)': { en: 'Total Revenue Mix by Match (Incl. Tix)', it: 'Mix Ricavi Totali per Partita (Incl. Biglietti)' },
  'Revenue Mix by Match (Excl. Tix)': { en: 'Revenue Mix by Match (Excl. Tix)', it: 'Mix Ricavi per Partita (Escl. Biglietti)' },
  'No GameDay data matches the current filters.': { en: 'No GameDay data matches the current filters.', it: 'Nessun dato GameDay corrisponde ai filtri attuali.' },
  'Total Net (Target 2.9M)': { en: 'Total Net (Target 2.9M)', it: 'Netto Totale (Obiettivo 2.9M)' },
  'Net excl. Tix (Target 1.25M)': { en: 'Net excl. Tix (Target 1.25M)', it: 'Netto escl. Biglietti (Obiettivo 1.25M)' },
  'Merch, F&B, Hosp, Park, Exp': { en: 'Merch, F&B, Hosp, Park, Exp', it: 'Merch, F&B, Osp, Park, Esp' },
  'Based on Total Tracked': { en: 'Based on Total Tracked', it: 'Basato sul Totale Tracciato' },
  'Allocated / Game': { en: 'Allocated / Game', it: 'Allocato / Partita' },
  'Excluded from this View': { en: 'Excluded from this View', it: 'Escluso da questa Vista' },
  'Mix': { en: 'Mix', it: 'Mix' },
  'SPH': { en: 'SPH', it: 'SPH' },

  'Sponsorship Analytics': { en: 'Sponsorship Analytics', it: 'Analisi Sponsorizzazioni' },
  'Revenue breakdown and sponsor portfolio analysis': { en: 'Revenue breakdown and sponsor portfolio analysis', it: 'Analisi portafoglio sponsor e scomposizione ricavi' },
  'Search sponsors...': { en: 'Search sponsors...', it: 'Cerca sponsor...' },
  'All Types': { en: 'All Types', it: 'Tutti i Tipi' },
  'Corp Tickets': { en: 'Corp Tickets', it: 'Biglietti Corporate' },
  'Game Day': { en: 'Game Day', it: 'GameDay' },
  'VB (Youth)': { en: 'VB (Youth)', it: 'VB (Giovanili)' },
  'CSR': { en: 'CSR', it: 'CSR' },
  'Cash': { en: 'Cash', it: 'Contanti' },
  'Cambio Merce': { en: 'Cambio Merce', it: 'Cambio Merce' },
  'Sector': { en: 'Sector', it: 'Settore' },
  'Company': { en: 'Company', it: 'Azienda' },
  'Commercial Value': { en: 'Commercial Value', it: 'Valore Commerciale' },
  'Contract Type': { en: 'Contract Type', it: 'Tipo Contratto' },
  'Deal Quality': { en: 'Deal Quality', it: 'Qualità Accordo' },
  'Sponsor Portfolio': { en: 'Sponsor Portfolio', it: 'Portafoglio Sponsor' },
  'Total Partners': { en: 'Total Partners', it: 'Partner Totali' },
  'Avg Deal Size': { en: 'Avg Deal Size', it: 'Dimensione Media Accordo' },
  'Cash Ratio': { en: 'Cash Ratio', it: 'Rapporto Contanti' },
  'Season Target': { en: 'Season Target', it: 'Obiettivo Stagione' },
  'Revenue Breakdown': { en: 'Revenue Breakdown', it: 'Scomposizione Ricavi' },
  'Revenue Distribution': { en: 'Revenue Distribution', it: 'Distribuzione Ricavi' },
  'Sector Breakdown': { en: 'Sector Breakdown', it: 'Scomposizione per Settore' },
  'Monthly Collections': { en: 'Monthly Collections', it: 'Incassi Mensili' },
  'Tier Distribution': { en: 'Tier Distribution', it: 'Distribuzione per Fascia' },
  'Sponsor Table': { en: 'Sponsor Table', it: 'Tabella Sponsor' },
  'Top Sponsors': { en: 'Top Sponsors', it: 'Sponsor Principali' },
  'Reconciliation': { en: 'Reconciliation', it: 'Riconciliazione' },
  'Excellent': { en: 'Excellent', it: 'Eccellente' },
  'Good': { en: 'Good', it: 'Buono' },
  'Fair': { en: 'Fair', it: 'Nella Media' },
  'Below': { en: 'Below', it: 'Sotto Media' },
  'Poor': { en: 'Poor', it: 'Scarso' },
  'sponsors': { en: 'sponsors', it: 'sponsor' },
  'Sponsor Detail': { en: 'Sponsor Detail', it: 'Dettaglio Sponsor' },
  'Contract History': { en: 'Contract History', it: 'Storico Contratto' },
  'Payment Schedule': { en: 'Payment Schedule', it: 'Piano Pagamenti' },
  'Close': { en: 'Close', it: 'Chiudi' },
  'Paid': { en: 'Paid', it: 'Pagato' },
  'Due': { en: 'Due', it: 'Da Pagare' },
  'Current': { en: 'Current', it: 'Corrente' },

  'Venue Operations': { en: 'Venue Operations', it: 'Operazioni Arena' },
  'Event Pipeline': { en: 'Event Pipeline', it: 'Pipeline Eventi' },
  'Total Revenue (YTD)': { en: 'Total Revenue (YTD)', it: 'Ricavi Totali (Da Inizio Anno)' },
  'Season Budget': { en: 'Season Budget', it: 'Budget Stagionale' },
  'H2 Confirmed Pipeline': { en: 'H2 Confirmed Pipeline', it: 'Pipeline Confermata H2' },
  'Arena Occupancy': { en: 'Arena Occupancy', it: 'Occupazione Arena' },
  'H1 Budget': { en: 'H1 Budget', it: 'Budget H1' },
  'Campus Status': { en: 'Campus Status', it: 'Stato Campus' },
  'Fully operational': { en: 'Fully operational', it: 'Pienamente operativo' },
  'Active': { en: 'Active', it: 'Attivo' },
  'Financial Note': { en: 'Financial Note', it: 'Nota Finanziaria' },
  'Monthly Arena Usage': { en: 'Monthly Arena Usage', it: 'Utilizzo Arena Mensile' },
  'Event Type Breakdown': { en: 'Event Type Breakdown', it: 'Scomposizione per Tipo Evento' },
  'Monthly Event Detail': { en: 'Monthly Event Detail', it: 'Dettaglio Eventi Mensile' },
  'Compliance & Safety': { en: 'Compliance & Safety', it: 'Conformità e Sicurezza' },
  'Completed': { en: 'Completed', it: 'Completato' },
  'Confirmed Revenue': { en: 'Confirmed Revenue', it: 'Ricavi Confermati' },
  'revenue events': { en: 'revenue events', it: 'eventi con ricavo' },
  'Community Events': { en: 'Community Events', it: 'Eventi Comunità' },
  'Zero cost to club (organizers cover expenses)': { en: 'Zero cost to club (organizers cover expenses)', it: 'Costo zero per il club (organizzatori coprono spese)' },
  'Unrealized / Lost': { en: 'Unrealized / Lost', it: 'Non Realizzati / Persi' },
  'deposit retained': { en: 'deposit retained', it: 'caparra trattenuta' },
  'Revenue-Generating Events': { en: 'Revenue-Generating Events', it: 'Eventi con Ricavo' },
  'Community & Youth Events': { en: 'Community & Youth Events', it: 'Eventi Comunità e Giovanili' },
  'Unrealized Opportunities': { en: 'Unrealized Opportunities', it: 'Opportunità Non Realizzate' },
  'No events scheduled': { en: 'No events scheduled', it: 'Nessun evento programmato' },
  'days used': { en: 'days used', it: 'giorni utilizzati' },
  'days': { en: 'days', it: 'giorni' },
  'of target': { en: 'of target', it: 'dell\'obiettivo' },
  'Revenue budget for H1': { en: 'Revenue budget for H1', it: 'Budget ricavi per H1' },
  'See note below': { en: 'See note below', it: 'Vedi nota sotto' },
  'Used': { en: 'Used', it: 'Utilizzato' },
  'Available': { en: 'Available', it: 'Disponibile' },
  'event': { en: 'event', it: 'evento' },
  'events': { en: 'events', it: 'eventi' },
  'Daily': { en: 'Daily', it: 'Giornaliero' },
  'Projected Total': { en: 'Projected Total', it: 'Totale Proiettato' },

  'BOps — Serie A': { en: 'BOps — Serie A', it: 'BOps — Serie A' },
  'Basketball Operations': { en: 'Basketball Operations', it: 'Operazioni Basket' },
  'H1 Revenue': { en: 'H1 Revenue', it: 'Ricavi H1' },
  'H1 Gap to Budget': { en: 'H1 Gap to Budget', it: 'Gap H1 vs Budget' },
  'below H1 target': { en: 'below H1 target', it: 'sotto l\'obiettivo H1' },
  'On or above target': { en: 'On or above target', it: 'In linea o sopra l\'obiettivo' },
  'Accounting Method': { en: 'Accounting Method', it: 'Metodo Contabile' },
  '4/10 Month Basis': { en: '4/10 Month Basis', it: 'Base 4/10 Mesi' },
  'Season Projection': { en: 'Season Projection', it: 'Proiezione Stagionale' },
  'H1 (4/10)': { en: 'H1 (4/10)', it: 'H1 (4/10)' },
  'H2 Remaining (6/10)': { en: 'H2 Remaining (6/10)', it: 'H2 Rimanente (6/10)' },
  'Season Target (label)': { en: 'Season Target', it: 'Obiettivo Stagionale' },
  'U26 Qualification Status': { en: 'U26 Qualification Status', it: 'Stato Qualificazione U26' },
  'Revenue Recognition': { en: 'Revenue Recognition', it: 'Riconoscimento Ricavi' },
  'Player buyout revenue': { en: 'Player buyout revenue', it: 'Ricavo buyout giocatore' },
  'Youth development allocation': { en: 'Youth development allocation', it: 'Allocazione sviluppo giovanile' },
  'League shared revenue pool': { en: 'League shared revenue pool', it: 'Fondo ricavi condiviso lega' },

  'Total Revenue (H1)': { en: 'Total Revenue (H1)', it: 'Ricavi Totali (H1)' },
  'H1 Variance': { en: 'H1 Variance', it: 'Varianza H1' },
  'Over budget': { en: 'Over budget', it: 'Sopra budget' },
  'Under budget – recoverable in H2': { en: 'Under budget – recoverable in H2', it: 'Sotto budget – recuperabile in H2' },
  'H2 Outlook': { en: 'H2 Outlook', it: 'Prospettive H2' },
  'Sponsorship Portfolio – H1': { en: 'Sponsorship Portfolio – H1', it: 'Portafoglio Sponsorizzazioni – H1' },
  'active sponsors': { en: 'active sponsors', it: 'sponsor attivi' },
  'H1 recognized': { en: 'H1 recognized', it: 'H1 riconosciuto' },
  'H1 Total from listed sponsors': { en: 'H1 Total from listed sponsors', it: 'Totale H1 da sponsor elencati' },
  'H2 Pipeline – New Business': { en: 'H2 Pipeline – New Business', it: 'Pipeline H2 – Nuovi Affari' },
  'Budget recovery': { en: 'Budget recovery', it: 'Recupero budget' },
  'Basketball Operations – H1 Breakdown': { en: 'Basketball Operations – H1 Breakdown', it: 'Operazioni Basket – Dettaglio H1' },
  'Player acquisitions, allocations & fees': { en: 'Player acquisitions, allocations & fees', it: 'Acquisizioni giocatori, allocazioni e commissioni' },
  'Budget Status': { en: 'Budget Status', it: 'Stato Budget' },
  'of H1 budget achieved': { en: 'of H1 budget achieved', it: 'del budget H1 raggiunto' },
  'On target': { en: 'On target', it: 'In linea con l\'obiettivo' },
  'of total': { en: 'of total', it: 'del totale' },
  'BOps H1 Total': { en: 'BOps H1 Total', it: 'BOps Totale H1' },
  'Elite Basketball Program – H1': { en: 'Elite Basketball Program – H1', it: 'Programma Elite Basket – H1' },
  'H1 total': { en: 'H1 total', it: 'Totale H1' },
  'of EBP revenue': { en: 'of EBP revenue', it: 'dei ricavi EBP' },
  'Total Players': { en: 'Total Players', it: 'Giocatori Totali' },
  'Enrolled in programs': { en: 'Enrolled in programs', it: 'Iscritti ai programmi' },
  'Avg Revenue / Player': { en: 'Avg Revenue / Player', it: 'Ricavo Medio / Giocatore' },
  'H1 average': { en: 'H1 average', it: 'Media H1' },
  'Programs': { en: 'Programs', it: 'Programmi' },
  'GameDay (Serie B)': { en: 'GameDay (Serie B)', it: 'GameDay (Serie B)' },
  'home games': { en: 'home games', it: 'partite in casa' },
  'Ticketing only': { en: 'Ticketing only', it: 'Solo biglietteria' },
  'of budget': { en: 'of budget', it: 'del budget' },
  '2 programs active': { en: '2 programs active', it: '2 programmi attivi' },
  'players enrolled': { en: 'players enrolled', it: 'giocatori iscritti' },

  'Avg Rev/Game': { en: 'Avg Rev/Game', it: 'Ricavo Medio/Partita' },
  'Yield (ATP)': { en: 'Yield (ATP)', it: 'Rendimento (ATP)' },
  'RevPAS': { en: 'RevPAS', it: 'RevPAS' },
  'Load Factor': { en: 'Load Factor', it: 'Fattore di Carico' },
  'Giveaway %': { en: 'Giveaway %', it: 'Omaggi %' },
  'Avg Attendance': { en: 'Avg Attendance', it: 'Presenza Media' },
  'Total Average': { en: 'Total Average', it: 'Media Totale' },
  'Per sold seat': { en: 'Per sold seat', it: 'Per posto venduto' },
  'Rev/Avail Seat': { en: 'Rev/Avail Seat', it: 'Ric/Posto Disponibile' },
  'Occupancy': { en: 'Occupancy', it: 'Occupazione' },
  'Tickets %': { en: 'Tickets %', it: 'Biglietti %' },
  'per game': { en: 'per game', it: 'per partita' },
  'vs prev season': { en: 'vs prev season', it: 'vs stagione precedente' },
  'vs KPIs': { en: 'vs KPIs', it: 'vs KPI' },
  'vs Max Target': { en: 'vs Max Target', it: 'vs Obiettivo Max' },

  'Revenue': { en: 'Revenue', it: 'Ricavi' },
  'Attendance': { en: 'Attendance', it: 'Presenze' },
  'Efficiency': { en: 'Efficiency', it: 'Efficienza' },

  'Season Overview': { en: 'Season Overview', it: 'Panoramica Stagione' },
  'Products': { en: 'Products', it: 'Prodotti' },
  'Orders': { en: 'Orders', it: 'Ordini' },
  'Customers': { en: 'Customers', it: 'Clienti' },
  'Inventory': { en: 'Inventory', it: 'Inventario' },
  'Community': { en: 'Community', it: 'Comunità' },
  'Season Revenue': { en: 'Season Revenue', it: 'Ricavi Stagione' },
  'Total Orders': { en: 'Total Orders', it: 'Ordini Totali' },
  'Avg Order Value': { en: 'Avg Order Value', it: 'Valore Medio Ordine' },
  'Total Products': { en: 'Total Products', it: 'Prodotti Totali' },
  'Season Goal': { en: 'Season Goal', it: 'Obiettivo Stagione' },
  'Revenue by Category': { en: 'Revenue by Category', it: 'Ricavi per Categoria' },
  'Monthly Revenue Trend': { en: 'Monthly Revenue Trend', it: 'Trend Ricavi Mensile' },
  'Top Products by Revenue': { en: 'Top Products by Revenue', it: 'Top Prodotti per Ricavo' },
  'Top Customers': { en: 'Top Customers', it: 'Top Clienti' },
  'Online Revenue': { en: 'Online Revenue', it: 'Ricavi Online' },
  'GameDay Merch': { en: 'GameDay Merch', it: 'Merch GameDay' },
  'Search products...': { en: 'Search products...', it: 'Cerca prodotti...' },
  'Search orders...': { en: 'Search orders...', it: 'Cerca ordini...' },
  'Search customers...': { en: 'Search customers...', it: 'Cerca clienti...' },
  'Product': { en: 'Product', it: 'Prodotto' },
  'Type': { en: 'Type', it: 'Tipo' },
  'Price': { en: 'Price', it: 'Prezzo' },
  'Stock': { en: 'Stock', it: 'Giacenza' },
  'Status': { en: 'Status', it: 'Stato' },
  'Order': { en: 'Order', it: 'Ordine' },
  'Date': { en: 'Date', it: 'Data' },
  'Customer': { en: 'Customer', it: 'Cliente' },
  'Items': { en: 'Items', it: 'Articoli' },
  'Net Total': { en: 'Net Total', it: 'Totale Netto' },
  'Payment': { en: 'Payment', it: 'Pagamento' },
  'Fulfillment': { en: 'Fulfillment', it: 'Evasione' },
  'Name': { en: 'Name', it: 'Nome' },
  'Email': { en: 'Email', it: 'Email' },
  'Spent': { en: 'Spent', it: 'Speso' },
  'Since': { en: 'Since', it: 'Da' },
  'Total Units': { en: 'Total Units', it: 'Unità Totali' },
  'Inventory Value': { en: 'Inventory Value', it: 'Valore Inventario' },
  'Out of Stock': { en: 'Out of Stock', it: 'Esaurito' },
  'Low Stock': { en: 'Low Stock', it: 'Scorte Basse' },
  'Healthy Stock': { en: 'Healthy Stock', it: 'Scorte Adeguate' },
  'Inventory by Category': { en: 'Inventory by Category', it: 'Inventario per Categoria' },
  'Category': { en: 'Category', it: 'Categoria' },
  'Units': { en: 'Units', it: 'Unità' },
  'Value': { en: 'Value', it: 'Valore' },
  'Load More': { en: 'Load More', it: 'Carica Altro' },
  'Exclude GameDay Merch': { en: 'Exclude GameDay Merch', it: 'Escludi Merch GameDay' },
  'Exclude Robur': { en: 'Exclude Robur', it: 'Escludi Robur' },
  'All Categories': { en: 'All Categories', it: 'Tutte le Categorie' },
  'Giveaways': { en: 'Giveaways', it: 'Omaggi' },
  'Recipient': { en: 'Recipient', it: 'Destinatario' },
  'Qty': { en: 'Qty', it: 'Qtà' },
  'Total Giveaways': { en: 'Total Giveaways', it: 'Totale Omaggi' },
  'recipients': { en: 'recipients', it: 'destinatari' },
  'Items Given': { en: 'Items Given', it: 'Articoli Donati' },
  'Opportunity Cost': { en: 'Opportunity Cost', it: 'Costo Opportunità' },
  'retail value': { en: 'retail value', it: 'valore al dettaglio' },
  'Avg per Recipient': { en: 'Avg per Recipient', it: 'Media per Destinatario' },
  'opportunity cost': { en: 'opportunity cost', it: 'costo opportunità' },
  'Giveaways by Recipient': { en: 'Giveaways by Recipient', it: 'Omaggi per Destinatario' },
  'No giveaways found for this season': { en: 'No giveaways found for this season', it: 'Nessun omaggio trovato per questa stagione' },
  'Revenue Center': { en: 'Revenue Center', it: 'Centro Ricavi' },
  'Cost Center': { en: 'Cost Center', it: 'Centro Costi' },
  'Verticals P&Ls': { en: 'Verticals P&Ls', it: 'P&L per Verticale' },
  'Track all revenue streams including ticketing, sponsorship, merchandising, game day operations, and more.': { en: 'Track all revenue streams including ticketing, sponsorship, merchandising, game day operations, and more.', it: 'Monitora tutti i flussi di ricavo inclusi biglietteria, sponsorizzazioni, merchandising, operazioni game day e altro.' },
  'Monitor and analyze operational costs, player salaries, facility expenses, and budget allocation.': { en: 'Monitor and analyze operational costs, player salaries, facility expenses, and budget allocation.', it: 'Monitora e analizza i costi operativi, stipendi dei giocatori, spese per le strutture e allocazione del budget.' },
  'Profit and loss analysis by business vertical — ticketing, sponsorship, merchandising, venue ops, and more.': { en: 'Profit and loss analysis by business vertical — ticketing, sponsorship, merchandising, venue ops, and more.', it: 'Analisi profitti e perdite per verticale di business — biglietteria, sponsorizzazioni, merchandising, venue ops e altro.' },
  'Comprehensive financial intelligence for Pallacanestro Varese': { en: 'Comprehensive financial intelligence for Pallacanestro Varese', it: 'Intelligence finanziaria completa per Pallacanestro Varese' },
  'Back to Financial Center': { en: 'Back to Financial Center', it: 'Torna al Centro Finanziario' },
  'This cost vertical is currently being integrated into the PV Financial Center.': { en: 'This cost vertical is currently being integrated into the PV Financial Center.', it: 'Questo verticale di costo è attualmente in fase di integrazione nel PV Financial Center.' },
  'BOps — Cost Structure': { en: 'BOps — Cost Structure', it: 'BOps — Struttura dei Costi' },
  'Full Season Cost Analysis': { en: 'Full Season Cost Analysis', it: 'Analisi Costi Stagione Completa' },
  'Total BOps Cost': { en: 'Total BOps Cost', it: 'Costo Totale BOps' },
  'vs prior season': { en: 'vs prior season', it: 'vs stagione precedente' },
  'Player Cost Share': { en: 'Player Cost Share', it: 'Quota Costi Giocatori' },
  'Net Salary to BOps Ratio': { en: 'Net Salary to BOps Ratio', it: 'Rapporto Stipendio Netto / BOps' },
  'Cost Distribution': { en: 'Cost Distribution', it: 'Distribuzione Costi' },
  'Total BOps Trend': { en: 'Total BOps Trend', it: 'Trend Totale BOps' },
  'Total BOps': { en: 'Total BOps', it: 'Totale BOps' },
  'Cost Type Breakdown by Season': { en: 'Cost Type Breakdown by Season', it: 'Scomposizione per Tipo di Costo per Stagione' },
  'Salaries': { en: 'Salaries', it: 'Stipendi' },
  'Taxes': { en: 'Taxes', it: 'Tasse' },
  'Agents': { en: 'Agents', it: 'Agenti' },
  'Related Costs': { en: 'Related Costs', it: 'Costi Correlati' },
  'A&R': { en: 'A&R', it: 'A&R' },
  'Luxury Tax': { en: 'Luxury Tax', it: 'Luxury Tax' },
  'Category Breakdown': { en: 'Category Breakdown', it: 'Scomposizione per Categoria' },
  'Players': { en: 'Players', it: 'Giocatori' },
  'Coaches': { en: 'Coaches', it: 'Allenatori' },
  'Management': { en: 'Management', it: 'Dirigenza' },
  'of category': { en: 'of category', it: 'della categoria' },
  'Players Related Cost': { en: 'Players Related Cost', it: 'Costi Correlati Giocatori' },
  'Coaches Related Cost': { en: 'Coaches Related Cost', it: 'Costi Correlati Allenatori' },
  'Management Related Cost': { en: 'Management Related Cost', it: 'Costi Correlati Dirigenza' },
  'Staff Related Cost': { en: 'Staff Related Cost', it: 'Costi Correlati Staff' },
  'Personnel': { en: 'Personnel', it: 'Personale' },
  'Software & Services': { en: 'Software & Services', it: 'Software e Servizi' },
  'Net Salary to BOps Ratio Trend': { en: 'Net Salary to BOps Ratio Trend', it: 'Trend Rapporto Stipendio Netto / BOps' },
  'Ratio': { en: 'Ratio', it: 'Rapporto' },
  'Season-over-Season Comparison': { en: 'Season-over-Season Comparison', it: 'Confronto Stagione su Stagione' },
  'Staff': { en: 'Staff', it: 'Staff' },
  'Monthly Actuals': { en: 'Monthly Actuals', it: 'Consuntivi Mensili' },
  'categories': { en: 'categories', it: 'categorie' },
  'Cost Structure': { en: 'Cost Structure', it: 'Struttura dei Costi' },
  'Total GameDay Cost': { en: 'Total GameDay Cost', it: 'Costo Totale GameDay' },
  'Peak Month': { en: 'Peak Month', it: 'Mese di Picco' },
  'Top Cost Category': { en: 'Top Cost Category', it: 'Categoria di Costo Principale' },
  'Monthly Cost Trend': { en: 'Monthly Cost Trend', it: 'Trend Costi Mensili' },
  'Full Cost Breakdown': { en: 'Full Cost Breakdown', it: 'Scomposizione Completa dei Costi' },
  'Top Cost Categories': { en: 'Top Cost Categories', it: 'Principali Categorie di Costo' },
  'Total GameDay': { en: 'Total GameDay', it: 'Totale GameDay' },
  'Tix Cost': { en: 'Tix Cost', it: 'Costo Biglietti' },
  'Tix Sales Ops': { en: 'Tix Sales Ops', it: 'Ops Vendita Biglietti' },
  'GD Merchandising': { en: 'GD Merchandising', it: 'Merchandising GD' },
  'Advertising Taxes': { en: 'Advertising Taxes', it: 'Tasse Pubblicitarie' },
  'GD Mkt - Materials and Advertising': { en: 'GD Mkt - Materials and Advertising', it: 'Mkt GD - Materiali e Pubblicità' },
  'Security and Safety': { en: 'Security and Safety', it: 'Sicurezza' },
  'GD Staff': { en: 'GD Staff', it: 'Staff GD' },
  'Cleaning': { en: 'Cleaning', it: 'Pulizia' },
  'Entertainment': { en: 'Entertainment', it: 'Intrattenimento' },
  'Penalties and Sanctions - Fans': { en: 'Penalties and Sanctions - Fans', it: 'Sanzioni e Penalità - Tifosi' },
  'GD Utilities': { en: 'GD Utilities', it: 'Utenze GD' },
  'Avg Cost / Game': { en: 'Avg Cost / Game', it: 'Costo Medio / Partita' },
  'across': { en: 'across', it: 'su' },
  'Most Efficient Month': { en: 'Most Efficient Month', it: 'Mese Più Efficiente' },
  'Most Efficient': { en: 'Most Efficient', it: 'Più Efficiente' },
  'Highest Cost Month': { en: 'Highest Cost Month', it: 'Mese Più Costoso' },
  'Highest Cost': { en: 'Highest Cost', it: 'Più Costoso' },
  'Events': { en: 'Events', it: 'Eventi' },
  'Materials & Ads': { en: 'Materials & Ads', it: 'Materiali e Pubblicità' },
  'Materials and Advertising': { en: 'Materials and Advertising', it: 'Materiali e Pubblicità' },
  'Category Split': { en: 'Category Split', it: 'Ripartizione per Categoria' },
  'Sponsorship cost breakdown by type': { en: 'Sponsorship cost breakdown by type', it: 'Scomposizione costi sponsorizzazione per tipo' },
  'Total Sponsorship': { en: 'Total Sponsorship', it: 'Totale Sponsorizzazione' },
  'Arena - Rental': { en: 'Arena - Rental', it: 'Arena - Affitto' },
  'Campus - Rental': { en: 'Campus - Rental', it: 'Campus - Affitto' },
  'Certification/Licensure Costs': { en: 'Certification/Licensure Costs', it: 'Costi Certificazione/Licenze' },
  'Arena Events Additional Costs': { en: 'Arena Events Additional Costs', it: 'Costi Aggiuntivi Eventi Arena' },
  'Insurance': { en: 'Insurance', it: 'Assicurazione' },
  'Avg Monthly': { en: 'Avg Monthly', it: 'Media Mensile' },
  'months': { en: 'months', it: 'mesi' },
  'Top Category': { en: 'Top Category', it: 'Categoria Principale' },
  'Cost by Category': { en: 'Cost by Category', it: 'Costo per Categoria' },
  'Total Venue Ops': { en: 'Total Venue Ops', it: 'Totale Venue Ops' },
  'Stock': { en: 'Stock', it: 'Stock' },
  'Team Store, e-Commerce Ops': { en: 'Team Store, e-Commerce Ops', it: 'Team Store, Ops e-Commerce' },
  'Customization': { en: 'Customization', it: 'Personalizzazione' },
  'Sales Ops': { en: 'Sales Ops', it: 'Ops Vendita' },
  'Ops Cost': { en: 'Ops Cost', it: 'Costo Ops' },
  'excl. Stock': { en: 'excl. Stock', it: 'escl. Stock' },
  'Total Merchandising': { en: 'Total Merchandising', it: 'Totale Merchandising' },
  'Aug spike': { en: 'Aug spike', it: 'Picco Ago' },
  'No costs recorded YTD': { en: 'No costs recorded YTD', it: 'Nessun costo registrato YTD' },
  'Zero Activity': { en: 'Zero Activity', it: 'Attività Zero' },
  'No EBP expenses have been recorded for the Jul–Dec 2025 period.': { en: 'No EBP expenses have been recorded for the Jul–Dec 2025 period.', it: 'Nessuna spesa EBP registrata per il periodo Lug–Dic 2025.' },
  'Cost of Sales': { en: 'Cost of Sales', it: 'Costo del Venduto' },
  'Direct costs tied to revenue verticals': { en: 'Direct costs tied to revenue verticals', it: 'Costi diretti legati ai verticali di ricavo' },
  'Total across verticals': { en: 'Total across verticals', it: 'Totale tra i verticali' },
  'YTD': { en: 'YTD', it: 'YTD' },
  'games': { en: 'games', it: 'partite' },
  'BOps prorated': { en: 'BOps prorated', it: 'BOps prorata' },
  'YTD Prorated': { en: 'YTD Prorated', it: 'YTD Prorata' },
  'SG&A': { en: 'SG&A', it: 'SG&A' },
  'Selling, General & Administrative': { en: 'Selling, General & Administrative', it: 'Vendite, Generali e Amministrative' },
  'SG&A cost tracking will be added here — overhead, admin, and general business expenses.': { en: 'SG&A cost tracking will be added here — overhead, admin, and general business expenses.', it: 'Il monitoraggio dei costi SG&A verrà aggiunto qui — spese generali, amministrative e aziendali.' },
  'Team Ops': { en: 'Team Ops', it: 'Ops Squadra' },
  'Labor': { en: 'Labor', it: 'Lavoro' },
  'Office': { en: 'Office', it: 'Ufficio' },
  'Maintenance': { en: 'Maintenance', it: 'Manutenzione' },
  'Financial': { en: 'Financial', it: 'Finanziario' },
  'Professional Services': { en: 'Professional Services', it: 'Servizi Professionali' },
  'Contingencies': { en: 'Contingencies', it: 'Contingenze' },
  'Travel': { en: 'Travel', it: 'Viaggi' },
  'Team Registration': { en: 'Team Registration', it: 'Registrazione Squadra' },
  'Travel - Flight': { en: 'Travel - Flight', it: 'Viaggio - Voli' },
  'Travel - Buses': { en: 'Travel - Buses', it: 'Viaggio - Bus' },
  'Travel - Vans': { en: 'Travel - Vans', it: 'Viaggio - Furgoni' },
  'Travel - Accommodation': { en: 'Travel - Accommodation', it: 'Viaggio - Alloggio' },
  'Team Gear': { en: 'Team Gear', it: 'Attrezzatura Squadra' },
  'Medical Expenses': { en: 'Medical Expenses', it: 'Spese Mediche' },
  'Immigration Processing Costs': { en: 'Immigration Processing Costs', it: 'Costi Pratiche Immigrazione' },
  'Logistical': { en: 'Logistical', it: 'Logistica' },
  'Payroll Deductions': { en: 'Payroll Deductions', it: 'Trattenute Stipendio' },
  'Penalties and Sanctions': { en: 'Penalties and Sanctions', it: 'Penalità e Sanzioni' },
  'Travel Total': { en: 'Travel Total', it: 'Totale Viaggi' },
  'Total Team Ops': { en: 'Total Team Ops', it: 'Totale Ops Squadra' },
  'Executive': { en: 'Executive', it: 'Dirigenza' },
  'Admin': { en: 'Admin', it: 'Amministrazione' },
  'Total Labor Cost': { en: 'Total Labor Cost', it: 'Costo Totale Lavoro' },
  'Costo Aziendale': { en: 'Company Cost', it: 'Costo Aziendale' },
  'Headcount': { en: 'Headcount', it: 'Organico' },
  'departments': { en: 'departments', it: 'dipartimenti' },
  'employees': { en: 'employees', it: 'dipendenti' },
  'Avg Cost / Employee': { en: 'Avg Cost / Employee', it: 'Costo Medio / Dipendente' },
  'Net Salary Total': { en: 'Net Salary Total', it: 'Totale Stipendio Netto' },
  'Net Salary': { en: 'Net Salary', it: 'Stipendio Netto' },
  'Taxes': { en: 'Taxes', it: 'Tasse' },
  'Employee Related Cost': { en: 'Employee Related Cost', it: 'Costi Relativi Dipendente' },
  'emp': { en: 'emp', it: 'dip' },
  'Department': { en: 'Department', it: 'Dipartimento' },
  'Department Breakdown': { en: 'Department Breakdown', it: 'Dettaglio per Dipartimento' },
  'Cost Composition': { en: 'Cost Composition', it: 'Composizione Costi' },
  'Cost by Department': { en: 'Cost by Department', it: 'Costo per Dipartimento' },
  'Employees': { en: 'Employees', it: 'Dipendenti' },
  'Prorated from annual': { en: 'Prorated from annual', it: 'Prorata da annuale' },
  'Annual': { en: 'Annual', it: 'Annuale' },
  'Monthly Cost vs Games': { en: 'Monthly Cost vs Games', it: 'Costo Mensile vs Partite' },
  'Bars = total cost · Labels = number of games': { en: 'Bars = total cost · Labels = number of games', it: 'Barre = costo totale · Etichette = numero partite' },
  'Cost per Game by Month': { en: 'Cost per Game by Month', it: 'Costo per Partita per Mese' },
  'Normalized view — higher is less efficient': { en: 'Normalized view — higher is less efficient', it: 'Vista normalizzata — più alto = meno efficiente' },
  'Cost per Game by Category': { en: 'Cost per Game by Category', it: 'Costo per Partita per Categoria' },
  'Average cost per game across': { en: 'Average cost per game across', it: 'Costo medio per partita su' },
  'Click to filter table below': { en: 'Click to filter table below', it: 'Clicca per filtrare la tabella sotto' },
  'Show All': { en: 'Show All', it: 'Mostra Tutti' },
  'Games': { en: 'Games', it: 'Partite' },
  'Cost/Game': { en: 'Cost/Game', it: 'Costo/Partita' },
  'Total Cost': { en: 'Total Cost', it: 'Costo Totale' },
  'Game': { en: 'Game', it: 'Partita' },
  'July': { en: 'July', it: 'Luglio' },
  'August': { en: 'August', it: 'Agosto' },
  'September': { en: 'September', it: 'Settembre' },
  'October': { en: 'October', it: 'Ottobre' },
  'November': { en: 'November', it: 'Novembre' },
  'December': { en: 'December', it: 'Dicembre' },
  '4-Season Growth': { en: '4-Season Growth', it: 'Crescita 4 Stagioni' },
  'BOps Cost Trend': { en: 'BOps Cost Trend', it: 'Trend Costi BOps' },
  'View Full BOps Dashboard': { en: 'View Full BOps Dashboard', it: 'Visualizza Dashboard BOps Completa' },
  'Detailed category breakdowns, sub-cost analysis, and ratio trends': { en: 'Detailed category breakdowns, sub-cost analysis, and ratio trends', it: 'Scomposizioni dettagliate per categoria, analisi sub-costi e trend dei rapporti' },
  'Other Cost Verticals': { en: 'Other Cost Verticals', it: 'Altri Verticali di Costo' },
  'Exclude VB': { en: 'Exclude VB', it: 'Escludi VB' },
  'Include GameDay Merch': { en: 'Include GameDay Merch', it: 'Includi Merch GameDay' },

  'Community Intelligence Hub': { en: 'Community Intelligence Hub', it: 'Hub Intelligence Comunità' },
  'RFM Segmentation': { en: 'RFM Segmentation', it: 'Segmentazione RFM' },
  'Champions': { en: 'Champions', it: 'Campioni' },
  'At Risk': { en: 'At Risk', it: 'A Rischio' },
  'New Blood': { en: 'New Blood', it: 'Nuovi Clienti' },
  'of customers': { en: 'of customers', it: 'dei clienti' },
  'N/A': { en: 'N/A', it: 'N/D' },
  'Gateway Products': { en: 'Gateway Products', it: 'Prodotti Gateway' },
  'Bundle Analysis': { en: 'Bundle Analysis', it: 'Analisi Bundle' },
  'Cohort Retention': { en: 'Cohort Retention', it: 'Retention Coorte' },

  'Total Tickets': { en: 'Total Tickets', it: 'Biglietti Totali' },
  'Total Revenue (label)': { en: 'Total Revenue', it: 'Ricavi Totali' },
  'Unique Customers': { en: 'Unique Customers', it: 'Clienti Unici' },
  'Avg Per Game': { en: 'Avg Per Game', it: 'Media per Partita' },
  'Zone Breakdown': { en: 'Zone Breakdown', it: 'Dettaglio per Zona' },
  'Sales Channel': { en: 'Sales Channel', it: 'Canale Vendita' },
  'Revenue by Zone': { en: 'Revenue by Zone', it: 'Ricavi per Zona' },
  'Revenue by Channel': { en: 'Revenue by Channel', it: 'Ricavi per Canale' },
  'Customer Analytics': { en: 'Customer Analytics', it: 'Analisi Clienti' },
  'Demographics': { en: 'Demographics', it: 'Demografica' },
  'Behavioral': { en: 'Behavioral', it: 'Comportamentale' },
  'Corporate': { en: 'Corporate', it: 'Corporate' },
  'Capacity': { en: 'Capacity', it: 'Capacità' },
  'Fixed': { en: 'Fixed', it: 'Fisso' },
  'Flexible': { en: 'Flexible', it: 'Flessibile' },
  'tickets': { en: 'tickets', it: 'biglietti' },

  'Loading data...': { en: 'Loading data...', it: 'Caricamento dati...' },
  'Loading...': { en: 'Loading...', it: 'Caricamento...' },
  'No data available': { en: 'No data available', it: 'Nessun dato disponibile' },
  'Error': { en: 'Error', it: 'Errore' },
  'Retry': { en: 'Retry', it: 'Riprova' },
  'of': { en: 'of', it: 'di' },
  'and': { en: 'and', it: 'e' },

  'Total': { en: 'Total', it: 'Totale' },
  'Average': { en: 'Average', it: 'Media' },
  'Budget': { en: 'Budget', it: 'Budget' },
  'Actual': { en: 'Actual', it: 'Effettivo' },
  'Variance': { en: 'Variance', it: 'Varianza' },
  'Annual': { en: 'Annual', it: 'Annuale' },

  'Switch to Light Mode': { en: 'Switch to Light Mode', it: 'Passa a Modalità Chiara' },
  'Switch to Dark Mode': { en: 'Switch to Dark Mode', it: 'Passa a Modalità Scura' },
  'Switch to Italian': { en: 'Switch to Italian', it: 'Passa a Italiano' },
  'Passa a Inglese': { en: 'Switch to English', it: 'Passa a Inglese' },

  'Showing': { en: 'Showing', it: 'Visualizzati' },
  'Showing all': { en: 'Showing all', it: 'Visualizzati tutti' },
  'results': { en: 'results', it: 'risultati' },
  'No results found': { en: 'No results found', it: 'Nessun risultato trovato' },
  'records': { en: 'records', it: 'record' },

  'Click any chart element to filter': { en: 'Click any chart element to filter', it: 'Clicca su un elemento del grafico per filtrare' },
  'contracts': { en: 'contracts', it: 'contratti' },
  'companies': { en: 'companies', it: 'aziende' },
  'Brand visibility, jersey/arena signage, media exposure': { en: 'Brand visibility, jersey/arena signage, media exposure', it: 'Visibilità del brand, segnaletica maglia/arena, esposizione mediatica' },
  'Youth team sponsorship, academy branding': { en: 'Youth team sponsorship, academy branding', it: 'Sponsorizzazione squadra giovanile, branding accademia' },
  'Corporate social responsibility activities': { en: 'Corporate social responsibility activities', it: 'Attività di responsabilità sociale d\'impresa' },
  'Tickets, parking, VIP access, hospitality (x15 games)': { en: 'Tickets, parking, VIP access, hospitality (x15 games)', it: 'Biglietti, parcheggio, accesso VIP, ospitalità (x15 partite)' },
  'GameDay Visibility': { en: 'GameDay Visibility', it: 'Visibilità GameDay' },
  'LED displays, naming rights, jersey, banners (x15 games)': { en: 'LED displays, naming rights, jersey, banners (x15 games)', it: 'Display LED, naming rights, maglia, striscioni (x15 partite)' },
  'Delta': { en: 'Delta', it: 'Delta' },
  'margin': { en: 'margin', it: 'margine' },
  'orders': { en: 'orders', it: 'ordini' },
  'revenue': { en: 'revenue', it: 'ricavi' },
  'Filtered': { en: 'Filtered', it: 'Filtrato' },
  'Updated': { en: 'Updated', it: 'Aggiornato' },
  'Online Sales': { en: 'Online Sales', it: 'Vendite Online' },
  'GameDay Sales': { en: 'GameDay Sales', it: 'Vendite GameDay' },
  'units sold': { en: 'units sold', it: 'unità vendute' },
  'for season': { en: 'for season', it: 'per la stagione' },
  'Found': { en: 'Found', it: 'Trovati' },
  'customers matching': { en: 'customers matching', it: 'clienti corrispondenti a' },
  'showing': { en: 'showing', it: 'visualizzati' },
  'customers': { en: 'customers', it: 'clienti' },
  'total products': { en: 'total products', it: 'prodotti totali' },
  'products': { en: 'products', it: 'prodotti' },
  'units': { en: 'units', it: 'unità' },
  'low stock items': { en: 'low stock items', it: 'articoli in esaurimento' },
  'out of stock items': { en: 'out of stock items', it: 'articoli esauriti' },
  'healthy': { en: 'healthy', it: 'disponibile' },
  'All seasons': { en: 'All seasons', it: 'Tutte le stagioni' },
  'unique customers': { en: 'unique customers', it: 'clienti unici' },
  'repeat customers': { en: 'repeat customers', it: 'clienti abituali' },
  'total': { en: 'total', it: 'totale' },
  'products in this category': { en: 'products in this category', it: 'prodotti in questa categoria' },
  'variant': { en: 'variant', it: 'variante' },
  'variants_plural': { en: 'variants', it: 'varianti' },
  'in stock': { en: 'in stock', it: 'disponibili' },
  'No category': { en: 'No category', it: 'Nessuna categoria' },
  'Guest': { en: 'Guest', it: 'Ospite' },
  'Unfulfilled': { en: 'Unfulfilled', it: 'Non evaso' },
  'Revenue_tooltip': { en: 'Revenue', it: 'Ricavi' },
  'SKU': { en: 'SKU', it: 'SKU' },

  'Achievement': { en: 'Achievement', it: 'Raggiungimento' },
  'AI Strategy Advisor': { en: 'AI Strategy Advisor', it: 'Consulente Strategico AI' },
  'Ask AI Advisor': { en: 'Ask AI Advisor', it: 'Chiedi al Consulente AI' },
  'Auto-synced from BigQuery': { en: 'Auto-synced from BigQuery', it: 'Sincronizzato automaticamente da BigQuery' },
  'Based on current run-rate extrapolation': { en: 'Based on current run-rate extrapolation', it: 'Basato sull\'estrapolazione del ritmo attuale' },
  'Connect Database': { en: 'Connect Database', it: 'Connetti Database' },
  'Corp Tickets in Ticketing (standard accounting view)': { en: 'Corp Tickets in Ticketing (standard accounting view)', it: 'Biglietti Corporate in Biglietteria (vista contabile standard)' },
  'Corp Tickets moved from Ticketing → Sponsorship (realistic view)': { en: 'Corp Tickets moved from Ticketing → Sponsorship (realistic view)', it: 'Biglietti Corporate spostati da Biglietteria → Sponsorizzazioni (vista realistica)' },
  'Count': { en: 'Count', it: 'Conteggio' },
  'Current Source': { en: 'Current Source', it: 'Fonte Attuale' },
  'Data Filters': { en: 'Data Filters', it: 'Filtri Dati' },
  'Data pipelines are under construction.': { en: 'Data pipelines are under construction.', it: 'Le pipeline dati sono in fase di costruzione.' },
  'Data Source Info': { en: 'Data Source Info', it: 'Info Fonte Dati' },
  'Day': { en: 'Day', it: 'Giorno' },
  'Detailed Games Log': { en: 'Detailed Games Log', it: 'Registro Dettagliato Partite' },
  'Discount Breakdown': { en: 'Discount Breakdown', it: 'Dettaglio Sconti' },
  'discounted tickets': { en: 'discounted tickets', it: 'biglietti scontati' },
  'F&B performance breakdown': { en: 'F&B performance breakdown', it: 'Dettaglio performance Food & Beverage' },
  'Fill %': { en: 'Fill %', it: 'Riemp. %' },
  'GameDay pacing and gap analysis': { en: 'GameDay pacing and gap analysis', it: 'Analisi ritmo e gap GameDay' },
  'Giveaway opportunity cost analysis': { en: 'Giveaway opportunity cost analysis', it: 'Analisi costo opportunità omaggi' },
  'Ignore Zona Ospiti': { en: 'Ignore Zona Ospiti', it: 'Ignora Zona Ospiti' },
  'Last Synced': { en: 'Last Synced', it: 'Ultima Sincronizzazione' },
  'Live from Shopify Admin API': { en: 'Live from Shopify Admin API', it: 'In tempo reale da Shopify Admin API' },
  'Loading sales data...': { en: 'Loading sales data...', it: 'Caricamento dati vendite...' },
  'Low occupancy zones strategy': { en: 'Low occupancy zones strategy', it: 'Strategia zone bassa occupazione' },
  'Match': { en: 'Match', it: 'Partita' },
  'Matches': { en: 'Matches', it: 'Partite' },
  'Merch sales by opponent analysis': { en: 'Merch sales by opponent analysis', it: 'Analisi vendite merch per avversario' },
  'Module In Development': { en: 'Module In Development', it: 'Modulo In Sviluppo' },
  'No data loaded': { en: 'No data loaded', it: 'Nessun dato caricato' },
  'No discounted tickets found': { en: 'No discounted tickets found', it: 'Nessun biglietto scontato trovato' },
  'Opponents': { en: 'Opponents', it: 'Avversari' },
  'Pace vs Time': { en: 'Pace vs Time', it: 'Ritmo vs Tempo' },
  'Powered by comprehensive business intelligence': { en: 'Powered by comprehensive business intelligence', it: 'Basato su business intelligence completa' },
  'Premium zone yield opportunities': { en: 'Premium zone yield opportunities', it: 'Opportunità rendimento zone premium' },
  'Projected': { en: 'Projected', it: 'Proiettato' },
  'Prorated': { en: 'Prorated', it: 'Pro-rata' },
  'Recognized YTD': { en: 'Recognized YTD', it: 'Riconosciuto YTD' },
  'Refresh Shopify Data': { en: 'Refresh Shopify Data', it: 'Aggiorna Dati Shopify' },
  'Reset View': { en: 'Reset View', it: 'Ripristina Vista' },
  'Rev %': { en: 'Rev %', it: 'Ric %' },
  'Sell': { en: 'Sell', it: 'Vendita' },
  'Signed (Full Year)': { en: 'Signed (Full Year)', it: 'Firmato (Anno Intero)' },
  'Sold/Cap': { en: 'Sold/Cap', it: 'Vend/Cap' },
  'Spend per head optimization opportunities': { en: 'Spend per head optimization opportunities', it: 'Opportunità ottimizzazione spesa per persona' },
  'Strategic Assessment': { en: 'Strategic Assessment', it: 'Valutazione Strategica' },
  'Sync All Data': { en: 'Sync All Data', it: 'Sincronizza Tutti i Dati' },
  'Syncing...': { en: 'Syncing...', it: 'Sincronizzazione...' },
  'This revenue vertical is currently being integrated into the PV Revenue Center.': { en: 'This revenue vertical is currently being integrated into the PV Revenue Center.', it: 'Questo verticale di ricavo è attualmente in fase di integrazione nel PV Revenue Center.' },
  'Ticketing pacing by zone': { en: 'Ticketing pacing by zone', it: 'Andamento biglietteria per zona' },
  'Total / Avg': { en: 'Total / Avg', it: 'Totale / Media' },
  'total tickets': { en: 'total tickets', it: 'biglietti totali' },
  'Trend': { en: 'Trend', it: 'Tendenza' },
  'Variable': { en: 'Variable', it: 'Variabile' },
  'View': { en: 'View', it: 'Vista' },
  'Yield': { en: 'Yield', it: 'Rendimento' },
  'YTD Collected': { en: 'YTD Collected', it: 'Incassato YTD' },
  'Zona Ospiti Excluded': { en: 'Zona Ospiti Excluded', it: 'Zona Ospiti Esclusa' },
  'Zones': { en: 'Zones', it: 'Zone' },

  'Loading CRM data...': { en: 'Loading CRM data...', it: 'Caricamento dati CRM...' },
  'BOps revenue is recognized on a': { en: 'BOps revenue is recognized on a', it: 'I ricavi BOps sono riconosciuti su base' },
  '4 out of 10 month': { en: '4 out of 10 month', it: '4 su 10 mesi' },
  'basis to align with the gameday revenue cycle. This ensures consistent period-over-period comparisons and matches the competitive season calendar.': { en: 'basis to align with the gameday revenue cycle. This ensures consistent period-over-period comparisons and matches the competitive season calendar.', it: 'per allinearsi al ciclo dei ricavi del giorno partita. Questo garantisce confronti coerenti tra periodi e corrisponde al calendario della stagione agonistica.' },
  'The': { en: 'The', it: 'Il' },
  'sponsorship gap will be recovered with the new Sports & Health (S&H) 3-year solar contract, bringing': { en: 'sponsorship gap will be recovered with the new Sports & Health (S&H) 3-year solar contract, bringing', it: 'gap sponsorizzazione sarà recuperato con il nuovo contratto solare triennale Sports & Health (S&H), portando' },
  'in H2. Additionally, the Finale Nazionali is backloaded into H2 — last season it generated': { en: 'in H2. Additionally, the Finale Nazionali is backloaded into H2 — last season it generated', it: 'in H2. Inoltre, le Finali Nazionali sono concentrate in H2 — la scorsa stagione hanno generato' },
  'with potential to improve this year. BOps is tracking at': { en: 'with potential to improve this year. BOps is tracking at', it: 'con possibilità di miglioramento quest\'anno. BOps sta procedendo al' },
  'The H1 gap of': { en: 'The H1 gap of', it: 'Il gap H1 di' },
  'vs budget will be fully covered by the S&H deal': { en: 'vs budget will be fully covered by the S&H deal', it: 'vs budget sarà completamente coperto dall\'accordo S&H' },
  'in H2': { en: 'in H2', it: 'in H2' },
  'resulting in a net surplus of': { en: 'resulting in a net surplus of', it: 'con un surplus netto di' },
  'for the season': { en: 'for the season', it: 'per la stagione' },
  'Player development revenue across': { en: 'Player development revenue across', it: 'Ricavi sviluppo giocatori su' },
  'enrolled players': { en: 'enrolled players', it: 'giocatori iscritti' },
  'Serie B Operations – Season 2025/26': { en: 'Serie B Operations – Season 2025/26', it: 'Operazioni Serie B – Stagione 2025/26' },
  'Jul – Dec 2025': { en: 'Jul – Dec 2025', it: 'Lug – Dic 2025' },
  'of annual target': { en: 'of annual target', it: 'dell\'obiettivo annuale' },
  'H2 recovery confirmed': { en: 'H2 recovery confirmed', it: 'Recupero H2 confermato' },
  'game': { en: 'game', it: 'partita' },
  'EBP': { en: 'EBP', it: 'EBP' },

  'Total Efficiency Matrix': { en: 'Total Efficiency Matrix', it: 'Matrice Efficienza Totale' },
  'GameDay Efficiency Matrix': { en: 'GameDay Efficiency Matrix', it: 'Matrice Efficienza GameDay' },
  'Occupancy %': { en: 'Occupancy %', it: 'Occupazione %' },
  'Yield (€)': { en: 'Yield (€)', it: 'Rendimento (€)' },
  'Premium': { en: 'Premium', it: 'Premium' },
  'Cash Cows': { en: 'Cash Cows', it: 'Cash Cow' },
  'Kill Zone': { en: 'Kill Zone', it: 'Zona Critica' },
  'Discount Trap': { en: 'Discount Trap', it: 'Trappola Sconto' },
  'View Mode': { en: 'View Mode', it: 'Modalità Vista' },
  'Tier Size': { en: 'Tier Size', it: 'Dimensione Fascia' },
  'Revenue vs Attendance Pacing': { en: 'Revenue vs Attendance Pacing', it: 'Andamento Ricavi vs Presenze' },
  'YoY History': { en: 'YoY History', it: 'Storico Anno su Anno' },
  'Forecast Line': { en: 'Forecast Line', it: 'Linea Previsione' },
  'Revenue (€)': { en: 'Revenue (€)', it: 'Ricavi (€)' },
  'Trend (Forecast)': { en: 'Trend (Forecast)', it: 'Trend (Previsione)' },
  'Tier Performance Analysis': { en: 'Tier Performance Analysis', it: 'Analisi Performance per Fascia' },
  'Avg Revenue': { en: 'Avg Revenue', it: 'Ricavo Medio' },
  'Avg PV Rank': { en: 'Avg PV Rank', it: 'Classifica PV Media' },
  'Day of Week Performance': { en: 'Day of Week Performance', it: 'Performance per Giorno della Settimana' },
  'Avg Attendance (chart)': { en: 'Avg Attendance', it: 'Presenza Media' },
  'Forecast': { en: 'Forecast', it: 'Previsione' },
  'Avg Rev': { en: 'Avg Rev', it: 'Ricavo Medio' },
  'Avg Att': { en: 'Avg Att', it: 'Presenza Media' },
  'Tier:': { en: 'Tier:', it: 'Fascia:' },
  'Occupancy:': { en: 'Occupancy:', it: 'Occupazione:' },
  'Yield (ATP):': { en: 'Yield (ATP):', it: 'Rendimento (ATP):' },
  'Revenue:': { en: 'Revenue:', it: 'Ricavi:' },
  'Season:': { en: 'Season:', it: 'Stagione:' },
  'Attendance:': { en: 'Attendance:', it: 'Presenze:' },
  'Forecast:': { en: 'Forecast:', it: 'Previsione:' },

  'Zone Efficiency Matrix': { en: 'Zone Efficiency Matrix', it: 'Matrice Efficienza Zone' },
  'Avg per game': { en: 'Avg per game', it: 'Media per partita' },
  'Avg Sold': { en: 'Avg Sold', it: 'Venduti Medi' },
  'Cap': { en: 'Cap', it: 'Cap' },
  'Avg Price': { en: 'Avg Price', it: 'Prezzo Medio' },
  'Rev Share': { en: 'Rev Share', it: 'Quota Ricavi' },
  'Fill Rate %': { en: 'Fill Rate %', it: 'Tasso Riemp. %' },
  'TOTAL / AVG': { en: 'TOTAL / AVG', it: 'TOTALE / MEDIA' },
  'Click to filter by this zone': { en: 'Click to filter by this zone', it: 'Clicca per filtrare per questa zona' },

  'Comparative Analysis': { en: 'Comparative Analysis', it: 'Analisi Comparativa' },
  'Analyzing GameDay revenue only (Variable)': { en: 'Analyzing GameDay revenue only (Variable)', it: 'Analisi solo ricavi GameDay (Variabili)' },
  'Analyze performance variance between two distinct datasets.': { en: 'Analyze performance variance between two distinct datasets.', it: 'Analizza la varianza di performance tra due dataset distinti.' },
  'Scenario': { en: 'Scenario', it: 'Scenario' },
  'Baseline': { en: 'Baseline', it: 'Riferimento' },
  'Total Revenue': { en: 'Total Revenue', it: 'Ricavi Totali' },
  'Avg Revenue / Game': { en: 'Avg Revenue / Game', it: 'Ricavo Medio / Partita' },
  'Revenue Comparison (Total)': { en: 'Revenue Comparison (Total)', it: 'Confronto Ricavi (Totale)' },
  'Scenario A': { en: 'Scenario A', it: 'Scenario A' },
  'Scenario B': { en: 'Scenario B', it: 'Scenario B' },
  'Select filters to begin comparison.': { en: 'Select filters to begin comparison.', it: 'Seleziona i filtri per iniziare il confronto.' },
  'Games matched': { en: 'Games matched', it: 'Partite trovate' },
  'Time': { en: 'Time', it: 'Orario' },

  'AI Consultant': { en: 'AI Consultant', it: 'Consulente AI' },
  'Live': { en: 'Live', it: 'In Diretta' },
  'Strategic Board Advisor • PV Engine': { en: 'Strategic Board Advisor • PV Engine', it: 'Consulente Strategico CDA • PV Engine' },
  'Consultant': { en: 'Consultant', it: 'Consulente' },
  'Director': { en: 'Director', it: 'Direttore' },
  'Consultant is analyzing scenarios...': { en: 'Consultant is analyzing scenarios...', it: 'Il consulente sta analizzando gli scenari...' },
  'Ask for strategic advice, revenue projections, or ticket pricing adjustment...': { en: 'Ask for strategic advice, revenue projections, or ticket pricing adjustment...', it: 'Chiedi consulenza strategica, proiezioni di ricavi o aggiustamenti dei prezzi dei biglietti...' },
  'AI insights are based on available historical data.': { en: 'AI insights are based on available historical data.', it: 'Le analisi AI sono basate sui dati storici disponibili.' },
  'Greetings. I am your AI Consultant. I have analyzed the current ticket sales and zone efficiency. How can we optimize yield for the next match?': { en: 'Greetings. I am your AI Consultant. I have analyzed the current ticket sales and zone efficiency. How can we optimize yield for the next match?', it: 'Salve. Sono il vostro Consulente AI. Ho analizzato le vendite biglietti attuali e l\'efficienza delle zone. Come possiamo ottimizzare il rendimento per la prossima partita?' },

  'Executive Briefing Generator': { en: 'Executive Briefing Generator', it: 'Generatore Briefing Esecutivo' },
  'Print / Save PDF': { en: 'Print / Save PDF', it: 'Stampa / Salva PDF' },
  'Commercial Performance Report': { en: 'Commercial Performance Report', it: 'Report Performance Commerciale' },
  'Report Date': { en: 'Report Date', it: 'Data Report' },
  'Strategic Status': { en: 'Strategic Status', it: 'Stato Strategico' },
  'Giveaway Rate': { en: 'Giveaway Rate', it: 'Tasso Omaggi' },
  'Last 5 Matches Performance': { en: 'Last 5 Matches Performance', it: 'Performance Ultime 5 Partite' },
  'Att.': { en: 'Att.', it: 'Pres.' },
  'Confidentiality Notice': { en: 'Confidentiality Notice', it: 'Avviso di Riservatezza' },
  'This document contains proprietary financial data of': { en: 'This document contains proprietary financial data of', it: 'Questo documento contiene dati finanziari riservati di' },
  'Unauthorized distribution is strictly prohibited.': { en: 'Unauthorized distribution is strictly prohibited.', it: 'La distribuzione non autorizzata è severamente vietata.' },
  'Data generated via PV Strategy AI Module.': { en: 'Data generated via PV Strategy AI Module.', it: 'Dati generati tramite il Modulo AI PV Strategy.' },
  'Generated by': { en: 'Generated by', it: 'Generato da' },
  'Page 1 of 1': { en: 'Page 1 of 1', it: 'Pagina 1 di 1' },

  'Strategy Simulator': { en: 'Strategy Simulator', it: 'Simulatore Strategico' },
  'Build a comprehensive pricing strategy.': { en: 'Build a comprehensive pricing strategy.', it: 'Costruisci una strategia di prezzo completa.' },
  'Summer (Season Tix)': { en: 'Summer (Season Tix)', it: 'Estate (Abbonamenti)' },
  'In-Season (Game Day)': { en: 'In-Season (Game Day)', it: 'In Stagione (Giorno Partita)' },
  'New Decision': { en: 'New Decision', it: 'Nuova Decisione' },
  'Price Adj. (€)': { en: 'Price Adj. (€)', it: 'Agg. Prezzo (€)' },
  'Demand Impact (%)': { en: 'Demand Impact (%)', it: 'Impatto Domanda (%)' },
  'Current Yield': { en: 'Current Yield', it: 'Rendimento Attuale' },
  'Proj. Impact': { en: 'Proj. Impact', it: 'Impatto Proiez.' },
  'CAPPED AT CAPACITY': { en: 'CAPPED AT CAPACITY', it: 'LIMITATO ALLA CAPACITÀ' },
  'OVERFLOW': { en: 'OVERFLOW', it: 'ECCEDENZA' },
  'DEMAND DROP': { en: 'DEMAND DROP', it: 'CALO DOMANDA' },
  'SEATS LOST': { en: 'SEATS LOST', it: 'POSTI PERSI' },
  'Add to Strategy': { en: 'Add to Strategy', it: 'Aggiungi alla Strategia' },
  'Baseline Rev (Avg)': { en: 'Baseline Rev (Avg)', it: 'Ricavo Base (Media)' },
  'Projected Rev (Avg)': { en: 'Projected Rev (Avg)', it: 'Ricavo Proiettato (Media)' },
  'Net Impact / Game': { en: 'Net Impact / Game', it: 'Impatto Netto / Partita' },
  'Season Est': { en: 'Season Est', it: 'Stima Stagione' },
  'Active Decisions': { en: 'Active Decisions', it: 'Decisioni Attive' },
  'Reset': { en: 'Reset', it: 'Ripristina' },
  'Applied': { en: 'Applied', it: 'Applicati' },
  'No decisions added yet.': { en: 'No decisions added yet.', it: 'Nessuna decisione aggiunta.' },
  'Vol': { en: 'Vol', it: 'Vol' },
  'seats': { en: 'seats', it: 'posti' },

  'Organizers cover all operational expenses (cleaning, utilities, staff), ensuring zero loss for the club.': { en: 'Organizers cover all operational expenses (cleaning, utilities, staff), ensuring zero loss for the club.', it: 'Gli organizzatori coprono tutte le spese operative (pulizia, utenze, personale), garantendo zero perdite per il club.' },
  'Community Events (Zero Net Cost)': { en: 'Community Events (Zero Net Cost)', it: 'Eventi Comunità (Costo Netto Zero)' },
  'Unrealized & Pending Opportunities': { en: 'Unrealized & Pending Opportunities', it: 'Opportunità Non Realizzate e In Sospeso' },
  'Total Confirmed Revenue': { en: 'Total Confirmed Revenue', it: 'Ricavi Confermati Totali' },
  'H1 Actual (Jul – Dec 2025)': { en: 'H1 Actual (Jul – Dec 2025)', it: 'H1 Effettivo (Lug – Dic 2025)' },
};

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  toggleLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('pv-language');
    return (saved === 'it' ? 'it' : 'en');
  });

  const toggleLanguage = () => {
    const next = language === 'en' ? 'it' : 'en';
    setLanguage(next);
    localStorage.setItem('pv-language', next);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
